version: '3.8'

services:
  postgres:
    image: postgres:alpine
    container_name: dev_pg
    environment:
      POSTGRES_DB: db_shipyard
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./src/sql/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
